
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author homer
 */
public class Vista extends javax.swing.JFrame {

    public static Conexion cone = new Conexion();
    public static int idc;
    public static String opc, aux;
    public static Object[] personas = new Object[6];

    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        consulta();
        PanelNumero.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Predicado = new javax.swing.JButton();
        PanelNumero = new javax.swing.JPanel();
        MenorQue = new javax.swing.JRadioButton();
        MayorQue = new javax.swing.JRadioButton();
        MenorIgualQue = new javax.swing.JRadioButton();
        MayorIgualQue = new javax.swing.JRadioButton();
        Igual = new javax.swing.JRadioButton();
        Diferente = new javax.swing.JRadioButton();
        Texto = new javax.swing.JTextField();
        nControl = new javax.swing.JCheckBox();
        Nombre = new javax.swing.JCheckBox();
        Domicilio = new javax.swing.JCheckBox();
        Ciudad = new javax.swing.JCheckBox();
        Edad = new javax.swing.JCheckBox();
        Oficio = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Control", "Nombre", "Domicilio ", "Ciudad", "Edad", "Oficio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tabla");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Predicado Simple ");

        Boton_Predicado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Boton_Predicado.setText("Pred. Simples");
        Boton_Predicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PredicadoActionPerformed(evt);
            }
        });

        buttonGroup2.add(MenorQue);
        MenorQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenorQue.setText("<");

        buttonGroup2.add(MayorQue);
        MayorQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MayorQue.setText(">");
        MayorQue.setToolTipText("");

        buttonGroup2.add(MenorIgualQue);
        MenorIgualQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenorIgualQue.setText("<=");

        buttonGroup2.add(MayorIgualQue);
        MayorIgualQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MayorIgualQue.setText(">=");

        buttonGroup2.add(Igual);
        Igual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Igual.setText("=");

        buttonGroup2.add(Diferente);
        Diferente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Diferente.setText("<>");

        javax.swing.GroupLayout PanelNumeroLayout = new javax.swing.GroupLayout(PanelNumero);
        PanelNumero.setLayout(PanelNumeroLayout);
        PanelNumeroLayout.setHorizontalGroup(
            PanelNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumeroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(MenorQue)
                .addGap(41, 41, 41)
                .addComponent(MayorQue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenorIgualQue)
                .addGap(51, 51, 51)
                .addComponent(MayorIgualQue)
                .addGap(54, 54, 54)
                .addComponent(Igual)
                .addGap(65, 65, 65)
                .addComponent(Diferente)
                .addGap(42, 42, 42))
        );
        PanelNumeroLayout.setVerticalGroup(
            PanelNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenorQue)
                    .addComponent(MayorQue)
                    .addComponent(MenorIgualQue)
                    .addComponent(MayorIgualQue)
                    .addComponent(Igual)
                    .addComponent(Diferente))
                .addGap(22, 22, 22))
        );

        Texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroup1.add(nControl);
        nControl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nControl.setText("No. Control");
        nControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nControlActionPerformed(evt);
            }
        });

        buttonGroup1.add(Nombre);
        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setText("Nombre");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(Domicilio);
        Domicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Domicilio.setText("Domicilio");
        Domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomicilioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Ciudad);
        Ciudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ciudad.setText("Ciudad");
        Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadActionPerformed(evt);
            }
        });

        buttonGroup1.add(Edad);
        Edad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edad.setText("Edad");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        buttonGroup1.add(Oficio);
        Oficio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Oficio.setText("Oficio");
        Oficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OficioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nControl)
                            .addComponent(Nombre)
                            .addComponent(Domicilio)
                            .addComponent(Ciudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Texto)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Edad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Oficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton_Predicado)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nControl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre))
                    .addComponent(PanelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Domicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ciudad))
                    .addComponent(Texto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Edad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Oficio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Predicado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nControlActionPerformed
        PanelNumero.setVisible(true);
        opc = "noControl";

    }//GEN-LAST:event_nControlActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        PanelNumero.setVisible(true);
        opc = "edad";

    }//GEN-LAST:event_EdadActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        PanelNumero.setVisible(false);
        opc = "nombre";

        aux = " = ";

    }//GEN-LAST:event_NombreActionPerformed

    private void DomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomicilioActionPerformed
        PanelNumero.setVisible(false);
        opc = "domicilio";
        aux = " = ";
    }//GEN-LAST:event_DomicilioActionPerformed

    private void CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadActionPerformed

        PanelNumero.setVisible(false);
        opc = "ciudad";
        aux = " = ";
    }//GEN-LAST:event_CiudadActionPerformed

    private void OficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OficioActionPerformed
        PanelNumero.setVisible(false);
        opc = "oficio";
        aux = " = ";
    }//GEN-LAST:event_OficioActionPerformed

    private void Boton_PredicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PredicadoActionPerformed

        fragmentacion();
    }//GEN-LAST:event_Boton_PredicadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    void consulta() {
        String sql = "SELECT * FROM personas";

        try {

            Connection conet = cone.getConnection();
            DefaultTableModel modelo;
            Statement st = conet.createStatement();
            ResultSet rs = st.executeQuery(sql);

            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                personas[0] = rs.getInt("noControl");
                personas[1] = rs.getString("nombre");
                personas[2] = rs.getString("domicilio");
                personas[3] = rs.getString("ciudad");
                personas[4] = rs.getInt("edad");
                personas[5] = rs.getString("oficio");

                modelo.addRow(personas);
            }

            Tabla.setModel(modelo);
            st.close();
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void fragmentacion() {

        String sql = "SELECT * FROM PERSONAS WHERE ";
        String auxInterfaz = Texto.getText();

        if (MenorQue.isSelected()) {
            aux = " < ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        } else if (MayorQue.isSelected()) {
            aux = " > ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        } else if (MenorIgualQue.isSelected()) {
            aux = " <= ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        } else if (MayorIgualQue.isSelected()) {
            aux = " >= ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        } else if (Diferente.isSelected()) {
            aux = " <> ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        } else if (Igual.isSelected()) {
            aux = " = ";
            sql += opc + aux + "'" + auxInterfaz + "'";
        }

        System.out.println(sql);

        try {
            Connection conet = cone.getConnection();
            DefaultTableModel modelo;
            Statement st = conet.createStatement();
            ResultSet rs = st.executeQuery(sql);
            modelo = new DefaultTableModel();
            modelo.addColumn("No. Columna");
            modelo.addColumn("Nombre");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Ciudad");
            modelo.addColumn("Edad");
            modelo.addColumn("Oficio");

            while (rs.next()) {
                personas[0] = rs.getInt("noControl");
                personas[1] = rs.getString("nombre");
                personas[2] = rs.getString("domicilio");
                personas[3] = rs.getString("ciudad");
                personas[4] = rs.getInt("edad");
                personas[5] = rs.getString("oficio");

                modelo.addRow(personas);
            }

            Tabla.setModel(modelo);
            st.close();
            rs.close();

            MenorQue.setSelected(false);
            MayorQue.setSelected(false);
            MenorIgualQue.setSelected(false);
            MayorIgualQue.setSelected(false);
            Igual.setSelected(false);
            Diferente.setSelected(false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Predicado;
    private javax.swing.JCheckBox Ciudad;
    private javax.swing.JRadioButton Diferente;
    private javax.swing.JCheckBox Domicilio;
    private javax.swing.JCheckBox Edad;
    private javax.swing.JRadioButton Igual;
    private javax.swing.JRadioButton MayorIgualQue;
    private javax.swing.JRadioButton MayorQue;
    private javax.swing.JRadioButton MenorIgualQue;
    private javax.swing.JRadioButton MenorQue;
    private javax.swing.JCheckBox Nombre;
    private javax.swing.JCheckBox Oficio;
    private javax.swing.JPanel PanelNumero;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Texto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox nControl;
    // End of variables declaration//GEN-END:variables
}
